name: receipe_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  stacked: ^3.4.1+1
  stacked_services: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  stacked_generator: ^1.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
flutter_intl:
  enabled: true
